### ISSUE TITLE
Replace the wl_spec_t variant with a class

### ISSUE THREAD

**Issue by seyhani** [all-things-networking/fperf#25]

**Comment by lucedes27** [comment]
+ Separate TimedSpec into one for queries (which accepts all derived classes) and one for search (which only accepts Comp)

**Comment by lucedes27** [comment]
Search TimedSpec only accepts COMP
Base workload TimedSpec accepts any WlSpec
We'll deal with Query later

Only difference between two TimedSpec is type of WlSpec accepted; better solution than separate classes?

If we want more than COMP in the Search TimedSpec, we want a way to be able to check in the Search TimedSpec constructor without if/else statements (variants vs. classes?)

**Comment by lucedes27** [comment]
Have each type of WlSpec keep track of whether it's available for search / base workload?
No need for separate TimedSpec classes?
Workload vs. SearchWorkload (static solution) which uses SearchTimedSpec or dynamically check with just the Workload class
