### ISSUE TITLE
Create classes for RHS, metric_t, ...

### ISSUE THREAD

**Issue by seyhani** [all-things-networking/fperf#30]

**Comment by lucedes27** [comment]
This is necessary to implement #29

**Comment by lucedes27** [comment]
Create classes for lhs_t, op_t, rhs_t, m_expr_t. @seyhani Is this it?

What about inheritance? Should they all inherit from some abstract class?

**Comment by seyhani** [comment]
The requirements are:
- we need a class for any workload language construct 
- Any class must be inherited from the abstract Node/Element class (not directly necessarily)
